import React from 'react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

export const metadata = {
  title: 'Disclaimer | KawalKontrak.ai',
};

export default function DisclaimerPage() {
  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <Header />
      <main style={{ flex: 1, padding: '80px 20px', maxWidth: '800px', margin: '0 auto', width: '100%' }}>
        <h1 style={{ fontSize: '32px', fontWeight: 'bold', marginBottom: '24px', color: 'var(--color-brand)' }}>Disclaimer</h1>
        <div style={{ lineHeight: '1.8', color: 'var(--color-neutral)', fontSize: '16px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <p>
            <strong>No Legal Advice</strong><br />
            The information and analysis provided by KawalKontrak.ai are generated by artificial intelligence and are intended for general informational purposes only. This service does not provide legal advice, and its outputs should not be construed as such.
          </p>
          <p>
            <strong>No Attorney-Client Relationship</strong><br />
            Your use of this service does not create an attorney-client relationship between you and KawalKontrak.ai or its developers. If you require legal advice, you should consult with a qualified attorney or legal professional in your jurisdiction.
          </p>
          <p>
            <strong>Accuracy and Reliability</strong><br />
            While we strive to provide accurate and up-to-date information based on Indonesian labor laws (UU Ketenagakerjaan), the AI may occasionally generate incorrect, incomplete, or outdated information. We make no warranties or representations regarding the accuracy, completeness, or reliability of the analysis provided.
          </p>
          <p>
            <strong>Limitation of Liability</strong><br />
            KawalKontrak.ai and its creators shall not be held liable for any direct, indirect, incidental, or consequential damages arising out of your use of or reliance on the information provided by this service. You are solely responsible for any decisions or actions you take based on the analysis.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
