import { LegalPageContent } from '@/components/LegalPageContent';

export const metadata = {
  title: 'Disclaimer | KawalKontrak.ai',
};

export default function DisclaimerPage() {
  return (
    <LegalPageContent
      title={{ en: 'Disclaimer', id: 'Penafian' }}
      sections={[
        {
          heading: { en: 'No Legal Advice', id: 'Bukan Nasihat Hukum' },
          body: {
            en: 'The information and analysis provided by KawalKontrak.ai are generated by artificial intelligence and are intended for general informational purposes only. This service does not provide legal advice, and its outputs should not be construed as such.',
            id: 'Informasi dan analisis yang disediakan oleh KawalKontrak.ai dihasilkan oleh kecerdasan buatan dan hanya ditujukan untuk keperluan informasi umum. Layanan ini tidak memberikan nasihat hukum, dan keluarannya tidak boleh ditafsirkan sebagai nasihat hukum.',
          },
        },
        {
          heading: { en: 'No Attorney-Client Relationship', id: 'Tidak Ada Hubungan Pengacara dan Klien' },
          body: {
            en: 'Your use of this service does not create an attorney-client relationship between you and KawalKontrak.ai or its developers. If you require legal advice, you should consult with a qualified attorney or legal professional in your jurisdiction.',
            id: 'Penggunaan layanan ini tidak menciptakan hubungan pengacara dan klien antara Anda dengan KawalKontrak.ai atau para pengembangnya. Jika Anda membutuhkan nasihat hukum, sebaiknya Anda berkonsultasi dengan pengacara atau profesional hukum yang berkualifikasi di wilayah hukum Anda.',
          },
        },
        {
          heading: { en: 'Accuracy and Reliability', id: 'Akurasi dan Keandalan' },
          body: {
            en: 'While we strive to provide accurate and up-to-date information based on Indonesian labor laws (UU Ketenagakerjaan), the AI may occasionally generate incorrect, incomplete, or outdated information. We make no warranties or representations regarding the accuracy, completeness, or reliability of the analysis provided.',
            id: 'Meskipun kami berupaya menyediakan informasi yang akurat dan terkini berdasarkan hukum ketenagakerjaan Indonesia (UU Ketenagakerjaan), AI terkadang dapat menghasilkan informasi yang keliru, tidak lengkap, atau sudah usang. Kami tidak memberikan jaminan atau pernyataan apa pun mengenai keakuratan, kelengkapan, atau keandalan analisis yang diberikan.',
          },
        },
        {
          heading: { en: 'Limitation of Liability', id: 'Batasan Tanggung Jawab' },
          body: {
            en: 'KawalKontrak.ai and its creators shall not be held liable for any direct, indirect, incidental, or consequential damages arising out of your use of or reliance on the information provided by this service. You are solely responsible for any decisions or actions you take based on the analysis.',
            id: 'KawalKontrak.ai dan para pembuatnya tidak bertanggung jawab atas segala kerugian langsung, tidak langsung, insidental, maupun konsekuensial yang timbul dari penggunaan atau ketergantungan Anda pada informasi yang disediakan oleh layanan ini. Anda sepenuhnya bertanggung jawab atas setiap keputusan atau tindakan yang Anda ambil berdasarkan analisis tersebut.',
          },
        },
      ]}
    />
  );
}
